#!/bin/bash

# if the first argument is "fresh" then it will remove any old folders and create a fresh set
if [ "$1" == "fresh" ]; then
  echo "Removing previously created folder"
  rm -r frontend
fi

# creates all the folders under the main folder frontend
echo "Creating folders"
declare -a arr=("frontend" "actions" "components" "reducers" "store" "util")

for i in "${arr[@]}"
do
  if [ ! -d "$i" ] && [ ! -d "frontend/$i" ]; then
    echo "Creating "$i""

    if [ "$i" == "frontend" ]; then
      mkdir "$i"
    else
      mkdir frontend/"$i"
    fi
  else
    echo ""$i" exists"
  fi
done

# move files from store location to correct director location
echo "Creating files"
for entry in "node_modules/react-jarb/boilerplate"/*;
do
  if [ -d "$entry" ]; then
    echo "Creating files for "$(basename $entry)""
    cp -R "$entry"/* "frontend/"$(basename $entry)"/"
  else
    cp "$entry" frontend/..
  fi
done


echo "Adding tests"
mkdir "frontend/components/__test__"
cp "node_modules/react-jarb/boilerplate/components/__test__/*" "frontend/components/__test__"
mkdir "frontend/reducers/__test__"
cp "node_modules/react-jarb/boilerplate/reducers/__test__/*" "frontend/reducers/__test__"


echo "Done."
